name: Staging Pipeline

on:
  push:
    branches:
      - "dev"
jobs:
  merge-branch:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: 'dev'
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'
          
      - uses: actions/checkout@v4
      - uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: 'dev'
          target_branch: 'release'
          commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'